### ISSUE TITLE
0.4  pip package is broken on Linux

### ISSUE THREAD

**Issue by mcsquaredjr** [catherinedevlin/ipython-sql#164]
'''
16:23:03     Complete output (5 lines):
16:23:03     Traceback (most recent call last):
16:23:03       File "<string>", line 1, in <module>
16:23:03       File "/tmp/pip-install-8eqKva/ipython-sql/setup.py", line 7, in <module>
16:23:03         NEWS = open(os.path.join(here, 'NEWS.rst'), encoding='utf-8').read()
16:23:03     IOError: [Errno 2] No such file or directory: '/tmp/pip-install-8eqKva/ipython-sql/NEWS.rst'
'''

**Comment by Sygyzmundovych** [comment]
@mcsquaredjr It seems that the issue with this version is only in Py2 now. As a workaround I used
```
pip install ipython-sql==0.3.9
```

**Comment by reductionista** [comment]
`pip install ipython-sql` doesn't work on OSX either (for python2).
Just noting here, in case someone thinks this is a Linux-specific issue.

`pip install ipython-sql==0.3.9` does work though

**Comment by Freso** [comment]
The issue is that `NEWS.rst` is not included in the source tarball uploaded to PyPI.
